repos:

  # ================
  # General
  # ================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=700']  # Increase the limit to 700 KB
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        auto-correct: true
        args: ['--fix=lf']
      - id: check-json
        name: Check JSON syntax

  # ================
  # Python
  # ================

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix, --config=pyproject.toml, --show-fixes ]
    - id: ruff-format
      args: [--config=pyproject.toml]

  - repo: https://github.com/astral-sh/ty-pre-commit
    # ty version.
    rev: v0.0.64
    hooks:
    - id: ty
